version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: ./docker/php/Dockerfile
        container_name: brooks_app
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        networks:
            - laravel

    nginx:
        image: nginx:stable
        container_name: brooks_nginx
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        networks:
            - laravel

    node:
        image: node:20-alpine
        container_name: brooks_node
        working_dir: /var/www
        volumes:
            - .:/var/www
        command: >
            sh -c "npm install && npm run build"
        networks:
            - laravel

    mysql:
        image: mysql:8.0
        container_name: brooks_mysql
        restart: unless-stopped
        ports:
            - "3307:3306" # avoids port clash with XAMPP or global MySQL
        environment:
            MYSQL_DATABASE: brooksgym_db
            MYSQL_ROOT_PASSWORD: myPassword1s!
        volumes:
            - mysql-data:/var/lib/mysql
        networks:
            - laravel

networks:
    laravel:
        driver: bridge

volumes:
    mysql-data:
